### ISSUE TITLE
Where can I find the GD.a file?

### ISSUE THREAD

**Issue by stefan89** [westmonroe/GoodDynamics_XamariniOSBinding#2]
Thanks for sharing this binding project!

Could you tell me where I can find the GD.a file? I've downloaded the 1.8.4334 version from:
https://community.good.com/docs/DOC-1052#jive_content_id_Version_18_Releases

When I install the downloaded package I look at the Good Technology folder but cannot find the GD.a file

Another question: do you have an updated version of this binding project to support the latest version of the Good Technology SDK? (v1.10)

Thanks in advance!

**Comment by peymanmortazavi** [comment]
You should download and install Good Kit (https://community.good.com/community/gdn/ios). After you install it, you can find the static source file in */Good Technology/Good.platform/Frameworks/GD.framework*

**Comment by stefan89** [comment]
![screen shot 2015-04-10 at 16 19 12](https://cloud.githubusercontent.com/assets/1457137/7089617/72624384-df9d-11e4-9d3a-0249785a4985.png)

I made a screenshot of the files I see in the folder. I don't see the GD.a file. I see a GD.exec file..

**Comment by peymanmortazavi** [comment]
it's that "GD" file (the very first file), you need to rename it to GD.a

**Comment by stefan89** [comment]
Thanks @peymanmortazavi
