### ISSUE TITLE
Does this binding project work with iOS SDK 8.3?

### ISSUE THREAD

**Issue by stefan89** [westmonroe/GoodDynamics_XamariniOSBinding#3]
Does this binding project work with iOS SDK 8.3?

I just tested this binding project example but I get a lot of errors.

Setup:
Xamarin.iOS version 8.9.1.3 (latest)
GOOD SDK version 1.8.4327
Build iOS SDK version 8.3 - uses Xcode 6.3
Deployment Target: iOS 7

**Comment by peymanmortazavi** [comment]
It works for me. Try target "Debug | iPhone", that's where all those compiler additional arguments are set. Also make sure it's set to Link All Assemblies. If it works, copy all that additional arguments and paste it for other targets as well. You may find your answer in this http://blog.westmonroepartners.com/using-good-dynamics-sdk-v1-8-x-with-xamarin-ios/

**Comment by stefan89** [comment]
Thanks, now I can build the example app. Unfortunately it does not run on a device.

Application output:
2015-04-16 13:31:29.381 GoodDynamicsExample[2389:1649318] [0375.711MB] [215%] [4] Library product line: GD version: 1.8.4327 (arm)
2015-04-16 13:31:29.382 GoodDynamicsExample[2389:1649318] [0375.715MB] [215%] [4] Origin ID: GD_SDK_for_iOS_Release_Dave-eng-mac12-4327
2015-04-16 13:31:29.383 GoodDynamicsExample[2389:1649318] [0375.715MB] [215%] [4] Source ID: 400195
2015-04-16 13:31:29.384 GoodDynamicsExample[2389:1649341] [0375.734MB] [215%] [4] Crypto: Initialising cryptographic systems...
2015-04-16 13:31:29.394 GoodDynamicsExample[2389:1649341] [0375.969MB] [215%] [4] Crypto: Cryptographics initialised.
2015-04-16 13:31:29.545 GoodDynamicsExample[2389:1649318] [0376.172MB] [215%] [2] Crypto::initialise: FIPS_mode_set failed: fingerprint does not match
2015-04-16 13:31:29.545 GoodDynamicsExample[2389:1649318] [0376.172MB] [215%] [2] IDeviceBase::initInstance FIPS initialisation failed


Is this a known error?

**Comment by peymanmortazavi** [comment]
Yes. http://blog.westmonroepartners.com/using-good-dynamics-sdk-v1-8-x-with-xamarin-ios/
Read the entire document, you're supposed to create some script files in FIBS folder in the Good Technology folder.

**Comment by stefan89** [comment]
I already did for all the architecture folders... 

The strange thing is that it looks like the Id file is a text file instead of an executable file. Although, when I double click on it, it will run in the terminal like a script.
![screen shot 2015-04-17 at 11 14 55](https://cloud.githubusercontent.com/assets/1457137/7199213/24f68032-e4f3-11e4-9643-2f1e5bb26eaa.png)

**Comment by stefan89** [comment]
I already did but it does not work

**Comment by stefan89** [comment]
Ah I used the wrong filename for "ld" files.

Now I can build the app on a physical device. However I get an error message in the app.

"Application Access Denied"
"The application is in simulation mode and cannot be run on a device"

I cannot find what this message mean. Is this message shown because I build it with a development provisioning profile?

**Comment by stefan89** [comment]
Never mind. In the info.plist file, the GDLibraryMode property was set to GDEnterpriseSimulation

**Comment by stefan89** [comment]
I've one question left... How do I get it work in the iOS Simulator?

I did the extra steps which are descripted in the blog but I get 45 errors when building for iOS simulator.

First I've added this line to the ld file:
NEW_ARGS=${NEW_ARGS//ios_simulator_version_min /mios-simulator-version-min=}
(see screenshot)
![screen shot 2015-04-17 at 12 18 41](https://cloud.githubusercontent.com/assets/1457137/7200298/f91a5138-e4fb-11e4-9f0a-de14f03718f6.png)

Then I've added this argument to the existing monotouch arguments:
--registrar:static
(see screenshot)
![screen shot 2015-04-17 at 12 15 02](https://cloud.githubusercontent.com/assets/1457137/7200322/25eeb49c-e4fc-11e4-8dcf-754255d54fe8.png)


Result:
![screen shot 2015-04-17 at 12 20 48](https://cloud.githubusercontent.com/assets/1457137/7200329/380e04c0-e4fc-11e4-98c2-be45755a2fca.png)
